In [1]:
import pandas as pd
from metadata_schemas.ai_taxonomy import get_ieee_tax, get_ieeefull_tax
from pprint import pprint
IEEE_TAX = get_ieee_tax()
IEEEFULL_TAX = get_ieeefull_tax()

In [2]:
ieee = pd.read_csv("../../../ieee_cl.csv")
ieee_10 = pd.read_csv("../../../ieee_cl10.csv")

In [3]:
ieee.index = "ieee_"+ieee.index.astype(str)

In [4]:
ieee

,IEEE Term,Document Title,Abstract,PDF Link,Author Keywords,IEEE Terms,Mesh_Terms
ieee_0,Accelerator architectures,Work-in-Progress: Ultra-fast yet Accurate Perf...,We present an automatic methodology to accurat...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;deep neural networks...,Deep learning;Analytical models;Runtime;Embedd...,NaN
ieee_1,Accelerator architectures,A Heterogeneous and Programmable Compute-In-Me...,We introduce a highly heterogeneous and progra...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;AI accelerators;hard...,System-on-chip;Computer architecture;Nonvolati...,NaN
ieee_2,Accelerator architectures,SCV-GNN: Sparse Compressed Vector-Based Graph ...,Graph neural networks (GNNs) have emerged as a...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;aggregation;graph ne...,Sparse matrices;Graph neural networks;Hardware...,NaN
ieee_3,Accelerator architectures,Sunstone: A Scalable and Versatile Scheduler f...,"Tensor algebra, the main component of several ...",https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,dataflow computing;accelerator architectures;s...,Tensors;Algebra;Software algorithms;Accelerato...,NaN
ieee_4,Accelerator architectures,Zebra: Leveraging Diagonal Attention Pattern f...,Vision Transformers (ViTs) have achieved remar...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;Attention mechanisms...,Computer vision;Accuracy;Runtime;Accelerator a...,NaN
...,...,...,...,...,...,...,...
ieee_55559,World Wide Web,MAX: wireless teleoperation via the World Wide...,The N-CART team has developed a working protot...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Web sites;Communication system control;Mobile ...,NaN
ieee_55560,World Wide Web,The History of Web Archiving,This paper describes the history and the curre...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Digital preservation;web archiving,Internet;Libraries;Information technology;Web ...,NaN
ieee_55561,World Wide Web,Web-based student modeling for learning multip...,This paper describes the development of web-ba...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Machine learning for user modeling;Student mod...,Adaptation models;Unified modeling language;Co...,NaN
ieee_55562,World Wide Web,Domain name based visualization of Web histori...,Users of hypertext systems like the World Wide...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Visualization;History;User interfaces;Tree gra...,NaN
ieee_55563,World Wide Web,A general framework for networked multimedia a...,The issue of accessing remote complex laborato...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Computer architecture;Proposals;Laboratories;P...,NaN

In [6]:
#ieee_10
ieee_abs = ieee.reset_index().set_index("Abstract")
ieee_10_abs = ieee_10.reset_index().set_index("Abstract")
ieee_10 = ieee_abs.loc[ieee_10_abs.index].reset_index().set_index("index")#.sort_index()

In [5]:
#ieee_10

In [7]:
#IEEE_TAX
ieee_strings = str(IEEE_TAX).split("'")[1::2]
ieeefull_strings = str(IEEEFULL_TAX).split("'")[1::2]

In [18]:
ieee_10

,Abstract,IEEE Term,Document Title,PDF Link,Author Keywords,IEEE Terms,Mesh_Terms
index,,,,,,,
ieee_0,We present an automatic methodology to accurat...,Accelerator architectures,Work-in-Progress: Ultra-fast yet Accurate Perf...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;deep neural networks...,Deep learning;Analytical models;Runtime;Embedd...,NaN
ieee_1,We introduce a highly heterogeneous and progra...,Accelerator architectures,A Heterogeneous and Programmable Compute-In-Me...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;AI accelerators;hard...,System-on-chip;Computer architecture;Nonvolati...,NaN
ieee_2,Graph neural networks (GNNs) have emerged as a...,Accelerator architectures,SCV-GNN: Sparse Compressed Vector-Based Graph ...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;aggregation;graph ne...,Sparse matrices;Graph neural networks;Hardware...,NaN
ieee_3,"Tensor algebra, the main component of several ...",Accelerator architectures,Sunstone: A Scalable and Versatile Scheduler f...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,dataflow computing;accelerator architectures;s...,Tensors;Algebra;Software algorithms;Accelerato...,NaN
ieee_4,Vision Transformers (ViTs) have achieved remar...,Accelerator architectures,Zebra: Leveraging Diagonal Attention Pattern f...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;Attention mechanisms...,Computer vision;Accuracy;Runtime;Accelerator a...,NaN
...,...,...,...,...,...,...,...
ieee_55506,With the explosive popularity of the internet ...,World Wide Web,Scalable web server design for distributed dat...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Web server;Internet;Load management;Home compu...,NaN
ieee_55507,Summary <p>The idea of the internet of things ...,World Wide Web,Data Communication and Information Exchange in...,https://ieeexplore.ieee.org/xpl/ebooks/bookPdf...,NaN,Internet of Things;Servers;Web 2.0;Real-time s...,NaN
ieee_55508,Most of the popular WWW search engines show th...,World Wide Web,Visualizing World-Wide Web search engine results,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Visualization;Web search;Search engines;Crawle...,NaN
ieee_55509,WWW's expansion coupled with high change frequ...,World Wide Web,A mathematical model for crawler revisit frequ...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,World Wide Web;Search engine;Mobile Crawler;Fr...,Mathematical model;Crawlers;Frequency;Uniform ...,NaN
ieee_55510,Caching has been recognized as one of the most...,World Wide Web,Impact of document types on the performance of...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Trace-driven simulation;caching algorithms;Wor...,World Wide Web;Network servers;Web server;Dela...,NaN

In [ ]:
ieee_ai_10 = ieee_10[ieee_10["IEEE Term"].isin(ieee_strings)]
ieee_ai_10.to_csv("../../../ieee_ai_cl10.csv", index=True)

In [8]:
ieeefull_10 = ieee_10[ieee_10["IEEE Term"].isin(ieeefull_strings)]
ieeefull_10.index = "full"+ieeefull_10.index.astype(str)
ieeefull_10.to_csv("../../../ieee_full_cl10.csv", index=True)
ieeefull_10

,Abstract,IEEE Term,Document Title,PDF Link,Author Keywords,IEEE Terms,Mesh_Terms
index,,,,,,,
fullieee_0,We present an automatic methodology to accurat...,Accelerator architectures,Work-in-Progress: Ultra-fast yet Accurate Perf...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;deep neural networks...,Deep learning;Analytical models;Runtime;Embedd...,NaN
fullieee_1,We introduce a highly heterogeneous and progra...,Accelerator architectures,A Heterogeneous and Programmable Compute-In-Me...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;AI accelerators;hard...,System-on-chip;Computer architecture;Nonvolati...,NaN
fullieee_2,Graph neural networks (GNNs) have emerged as a...,Accelerator architectures,SCV-GNN: Sparse Compressed Vector-Based Graph ...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;aggregation;graph ne...,Sparse matrices;Graph neural networks;Hardware...,NaN
fullieee_3,"Tensor algebra, the main component of several ...",Accelerator architectures,Sunstone: A Scalable and Versatile Scheduler f...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,dataflow computing;accelerator architectures;s...,Tensors;Algebra;Software algorithms;Accelerato...,NaN
fullieee_4,Vision Transformers (ViTs) have achieved remar...,Accelerator architectures,Zebra: Leveraging Diagonal Attention Pattern f...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;Attention mechanisms...,Computer vision;Accuracy;Runtime;Accelerator a...,NaN
...,...,...,...,...,...,...,...
fullieee_55506,With the explosive popularity of the internet ...,World Wide Web,Scalable web server design for distributed dat...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Web server;Internet;Load management;Home compu...,NaN
fullieee_55507,Summary <p>The idea of the internet of things ...,World Wide Web,Data Communication and Information Exchange in...,https://ieeexplore.ieee.org/xpl/ebooks/bookPdf...,NaN,Internet of Things;Servers;Web 2.0;Real-time s...,NaN
fullieee_55508,Most of the popular WWW search engines show th...,World Wide Web,Visualizing World-Wide Web search engine results,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Visualization;Web search;Search engines;Crawle...,NaN
fullieee_55509,WWW's expansion coupled with high change frequ...,World Wide Web,A mathematical model for crawler revisit frequ...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,World Wide Web;Search engine;Mobile Crawler;Fr...,Mathematical model;Crawlers;Frequency;Uniform ...,NaN
fullieee_55510,Caching has been recognized as one of the most...,World Wide Web,Impact of document types on the performance of...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Trace-driven simulation;caching algorithms;Wor...,World Wide Web;Network servers;Web server;Dela...,NaN

In [10]:
n=1
#ieee_10.groupby(["IEEE Term"]).sample(frac=n/10)
ieee_10.groupby(["IEEE Term"]).head(1)

,Abstract,IEEE Term,Document Title,PDF Link,Author Keywords,IEEE Terms,Mesh_Terms
index,,,,,,,
ieee_0,We present an automatic methodology to accurat...,Accelerator architectures,Work-in-Progress: Ultra-fast yet Accurate Perf...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Accelerator architectures;deep neural networks...,Deep learning;Analytical models;Runtime;Embedd...,NaN
ieee_50713,The one invited paper and four selected papers...,System buses,Accelerator Architectures,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,NaN,Accelerator architectures;Acceleration;Costs;G...,NaN
ieee_38395,Partial bitstream relocation (PBR) on FPGAs ha...,Performance analysis,PRR-PRR Dynamic Relocation,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Reconfigurable hardware;Emerging technologies;...,Field programmable gate arrays;Bioreactors;Cir...,NaN
ieee_87,"In recent years, deep learning-based medical i...",Active learning,Dual-Criteria Active Learning for Medical Imag...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,active learning;medical image segmentation;dee...,Training;Measurement;Deep learning;Image segme...,NaN
ieee_182,A 3D partitioned active shape model (PASM) is ...,Active shape model,Robust MR Image Segmentation Using 3D Partitio...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,3D MR image segmentation;Active Shape Model;Hi...,Image segmentation;Active shape model;Tiles;De...,NaN
...,...,...,...,...,...,...,...
ieee_54569,This article presents a novel PPG acquisition ...,Wearable Health Monitoring Systems,"A Multi-Site, Multi-Wavelength PPG Platform fo...",https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Biomedical monitoring;optical sensors;photople...,Biomedical monitoring;Optical sensors;Photople...,Male;Humans;Female;Pulse Wave Analysis;Photopl...
ieee_54638,Summary <p>Artificial Intelligence Marketing i...,Web conferencing,Impact of Artificial Intelligence on Digital M...,https://ieeexplore.ieee.org/xpl/ebooks/bookPdf...,NaN,Artificial intelligence;Machine learning;Engin...,NaN
ieee_54812,Semantic-Synaptic Web mining [1] aims to integ...,Web mining,Entropy measurement and algorithm for Semantic...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Entropy;Semantic Web;Semantic-Synaptic web;Sem...,Entropy;Web mining;Semantic Web;Web pages;Sema...,NaN
ieee_55216,Rogue Wi-Fi networks pose a significant threat...,Wireless access points,The Elusive Enigma: Unraveling Rogue Wi-Fi's C...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,Rogue Wi-Fi;Man-in-the-Middle Attacks;Rogue Ac...,Firewalls (computing);Data protection;Intrusio...,NaN
ieee_55309,Broadcast delivery of bulk multimedia files is...,Wireless LAN,Fair and Bandwidth-efficient Broadcast link ra...,https://ieeexplore.ieee.org/stamp/stamp.jsp?ar...,broadcast;wireless lan;link rate adaptation;fa...,Wireless LAN;Protocols;Bandwidth;Broadcasting;...,NaN

In [11]:
others = 0
for term in ieee["IEEE Term"]:
    if term in ieee_counts:
        ieee_counts[term] += 1
    else:
        others += 1
print(others)
pprint(ieee_counts)

43790
{'AI accelerators': 100,
 'Active learning': 95,
 'Adversarial machine learning': 95,
 'Affective computing': 100,
 'Artificial general intelligence': 87,
 'Artificial intelligence': 97,
 'Artificial neural networks': 99,
 'Association rule learning': 100,
 'Attention mechanisms': 98,
 'Autoencoders': 90,
 'Automated machine learning': 84,
 'Autonomous mental development': 24,
 'Autonomous robots': 100,
 'Autonomous systems': 100,
 'Backpropagation': 85,
 'Bidirectional long short term memory': 87,
 'Bio-inspired computing': 47,
 'Biological neural networks': 96,
 'Boosting': 99,
 'Cellular neural networks': 100,
 'Chatbots': 100,
 'Cognitive systems': 87,
 'Collective intelligence': 97,
 'Collective learning': 4,
 'Commonsense reasoning': 71,
 'Computation theory': 59,
 'Computational and artificial intelligence': 0,
 'Computational chemistry': 6,
 'Computational complexity': 100,
 'Computational cybernetics': 43,
 'Computational intelligence': 87,
 'Computational statistics': 6,
 'Concept drift': 81,
 'Concurrent computing': 73,
 'Context awareness': 99,
 'Context management': 13,
 'Conversational artificial intelligence': 46,
 'Convolutional neural networks': 100,
 'Cooperative systems': 97,
 'Deep learning': 100,
 'Deep reinforcement learning': 100,
 'Diffusion models': 100,
 'Dimensionality reduction': 99,
 'Echo state networks': 38,
 'Edge AI': 81,
 'Electronic learning': 80,
 'Ensemble learning': 96,
 'Evolutionary computation': 100,
 'Evolutionary robotics': 17,
 'Expert systems': 86,
 'Explainable AI': 100,
 'Extreme learning machines': 91,
 'Federated learning': 100,
 'Feedforward neural networks': 98,
 'Few shot learning': 100,
 'Foundation models': 100,
 'Fuzzy control': 100,
 'Fuzzy logic': 100,
 'Fuzzy neural networks': 100,
 'Fuzzy systems': 98,
 'Gated recurrent units': 100,
 'Generative AI': 100,
 'Generative Pre-trainer transformer': 59,
 'Genetic algorithms': 91,
 'Genetic operators': 69,
 'Graph convolutional networks': 95,
 'Graph neural networks': 100,
 'Greedy algorithms': 98,
 'Hebbian theory': 99,
 'High dimensional data': 37,
 'Hopfield neural networks': 95,
 'Hybrid intelligent systems': 98,
 'Hybrid learning': 94,
 'Hyper-intelligent systems': 4,
 'Hyperparameter optimization': 98,
 'Imitation learning': 89,
 'Immersive learning': 96,
 'Incremental learning': 98,
 'Inference mechanisms': 91,
 'Intelligent automation': 65,
 'Intelligent robots': 85,
 'Intelligent systems': 92,
 'Knowledge acquisition': 98,
 'Knowledge based systems': 74,
 'Knowledge discovery': 99,
 'Knowledge engineering': 79,
 'Knowledge representation': 100,
 'Large language models': 100,
 'Learning automata': 100,
 'Learning management systems': 100,
 'Learning systems': 90,
 'Linear predictive coding': 92,
 'Logic': 16,
 'Long short term memory': 84,
 'Machine intelligence': 83,
 'Machine learning': 96,
 'Machine listening': 58,
 'Mobile agents': 100,
 'Model compression': 77,
 'Multi-armed bandit problem': 55,
 'Multi-layer neural network': 99,
 'Multilayer perceptrons': 64,
 'Multivalued logic': 96,
 'Neural architecture search': 96,
 'Neural network compression': 47,
 'Neural network hardware': 80,
 'Neural networks': 54,
 'One shot learning': 33,
 'Particle swarm optimization': 100,
 'Pattern analysis': 75,
 'Perception evolution networks': 9,
 'Prediction methods': 100,
 'Predictive coding': 83,
 'Predictive encoding': 25,
 'Predictive models': 99,
 'Probabilistic logic': 93,
 'Prompt engineering': 100,
 'Radial basis function networks': 96,
 'Random forests': 93,
 'Recurrent neural networks': 99,
 'Reinforcement learning': 77,
 'Relevance vector machines': 40,
 'Representation learning': 100,
 'Reservoir computing': 99,
 'Residual neural networks': 97,
 'Retrieval augmented generation': 100,
 'Robot learning': 75,
 'Self-organizing feature maps': 47,
 'Self-supervised learning': 100,
 'Semisupervised learning': 100,
 'Spiking neural networks': 99,
 'Stability plasticity': 25,
 'Statistical learning': 97,
 'Sufficient conditions': 92,
 'Supervised learning': 86,
 'Support vector machines': 100,
 'Takagi-Sugeno model': 96,
 'Text to image': 99,
 'Text to video': 83,
 'Tiny machine learning': 71,
 'Transfer learning': 100,
 'Turing completeness': 5,
 'Unsupervised learning': 100,
 'Virtual artifact': 4,
 'Virtual assistants': 88,
 'Weak supervision': 63}

In [12]:
others = 0
for term in ieee_10["IEEE Term"]:
    if term in ieee_counts_10:
        ieee_counts_10[term] += 1
    else:
        others += 1
print(others)
pprint(ieee_counts_10)

6151
{'AI accelerators': 10,
 'Active learning': 11,
 'Adversarial machine learning': 10,
 'Affective computing': 12,
 'Artificial general intelligence': 11,
 'Artificial intelligence': 10,
 'Artificial neural networks': 10,
 'Association rule learning': 10,
 'Attention mechanisms': 12,
 'Autoencoders': 10,
 'Automated machine learning': 12,
 'Autonomous mental development': 10,
 'Autonomous robots': 10,
 'Autonomous systems': 10,
 'Backpropagation': 11,
 'Bidirectional long short term memory': 10,
 'Bio-inspired computing': 11,
 'Biological neural networks': 12,
 'Boosting': 10,
 'Cellular neural networks': 12,
 'Chatbots': 12,
 'Cognitive systems': 12,
 'Collective intelligence': 10,
 'Collective learning': 4,
 'Commonsense reasoning': 10,
 'Computation theory': 10,
 'Computational and artificial intelligence': 0,
 'Computational chemistry': 6,
 'Computational complexity': 11,
 'Computational cybernetics': 10,
 'Computational intelligence': 12,
 'Computational statistics': 6,
 'Concept drift': 10,
 'Concurrent computing': 18,
 'Context awareness': 13,
 'Context management': 10,
 'Conversational artificial intelligence': 10,
 'Convolutional neural networks': 13,
 'Cooperative systems': 11,
 'Deep learning': 10,
 'Deep reinforcement learning': 12,
 'Diffusion models': 11,
 'Dimensionality reduction': 15,
 'Echo state networks': 12,
 'Edge AI': 10,
 'Electronic learning': 18,
 'Ensemble learning': 11,
 'Evolutionary computation': 10,
 'Evolutionary robotics': 10,
 'Expert systems': 10,
 'Explainable AI': 10,
 'Extreme learning machines': 11,
 'Federated learning': 10,
 'Feedforward neural networks': 12,
 'Few shot learning': 11,
 'Foundation models': 10,
 'Fuzzy control': 10,
 'Fuzzy logic': 10,
 'Fuzzy neural networks': 10,
 'Fuzzy systems': 10,
 'Gated recurrent units': 11,
 'Generative AI': 10,
 'Generative Pre-trainer transformer': 11,
 'Genetic algorithms': 15,
 'Genetic operators': 10,
 'Graph convolutional networks': 10,
 'Graph neural networks': 10,
 'Greedy algorithms': 10,
 'Hebbian theory': 10,
 'High dimensional data': 10,
 'Hopfield neural networks': 13,
 'Hybrid intelligent systems': 12,
 'Hybrid learning': 10,
 'Hyper-intelligent systems': 4,
 'Hyperparameter optimization': 12,
 'Imitation learning': 10,
 'Immersive learning': 11,
 'Incremental learning': 10,
 'Inference mechanisms': 10,
 'Intelligent automation': 10,
 'Intelligent robots': 10,
 'Intelligent systems': 11,
 'Knowledge acquisition': 10,
 'Knowledge based systems': 10,
 'Knowledge discovery': 11,
 'Knowledge engineering': 15,
 'Knowledge representation': 14,
 'Large language models': 11,
 'Learning automata': 10,
 'Learning management systems': 11,
 'Learning systems': 11,
 'Linear predictive coding': 11,
 'Logic': 10,
 'Long short term memory': 10,
 'Machine intelligence': 11,
 'Machine learning': 10,
 'Machine listening': 10,
 'Mobile agents': 10,
 'Model compression': 10,
 'Multi-armed bandit problem': 10,
 'Multi-layer neural network': 12,
 'Multilayer perceptrons': 11,
 'Multivalued logic': 10,
 'Neural architecture search': 10,
 'Neural network compression': 11,
 'Neural network hardware': 10,
 'Neural networks': 18,
 'One shot learning': 13,
 'Particle swarm optimization': 10,
 'Pattern analysis': 10,
 'Perception evolution networks': 9,
 'Prediction methods': 10,
 'Predictive coding': 10,
 'Predictive encoding': 10,
 'Predictive models': 10,
 'Probabilistic logic': 10,
 'Prompt engineering': 11,
 'Radial basis function networks': 11,
 'Random forests': 10,
 'Recurrent neural networks': 16,
 'Reinforcement learning': 11,
 'Relevance vector machines': 10,
 'Representation learning': 10,
 'Reservoir computing': 10,
 'Residual neural networks': 11,
 'Retrieval augmented generation': 10,
 'Robot learning': 10,
 'Self-organizing feature maps': 10,
 'Self-supervised learning': 18,
 'Semisupervised learning': 10,
 'Spiking neural networks': 10,
 'Stability plasticity': 11,
 'Statistical learning': 10,
 'Sufficient conditions': 10,
 'Supervised learning': 17,
 'Support vector machines': 10,
 'Takagi-Sugeno model': 10,
 'Text to image': 11,
 'Text to video': 11,
 'Tiny machine learning': 10,
 'Transfer learning': 10,
 'Turing completeness': 5,
 'Unsupervised learning': 10,
 'Virtual artifact': 4,
 'Virtual assistants': 11,
 'Weak supervision': 10}

In [13]:
others = 0
for terms in ieee["IEEE Terms"]:
    for term in terms.split(";"):
        if term in ieee_terms_counts:
            ieee_terms_counts[term] += 1
        else:
            others += 1
print(others)
pprint(ieee_terms_counts)

418019
{'AI accelerators': 110,
 'Active learning': 108,
 'Adversarial machine learning': 103,
 'Affective computing': 115,
 'Artificial general intelligence': 92,
 'Artificial intelligence': 1252,
 'Artificial neural networks': 889,
 'Association rule learning': 109,
 'Attention mechanisms': 242,
 'Autoencoders': 140,
 'Automated machine learning': 99,
 'Autonomous mental development': 24,
 'Autonomous robots': 117,
 'Autonomous systems': 149,
 'Backpropagation': 159,
 'Bidirectional long short term memory': 99,
 'Bio-inspired computing': 49,
 'Biological neural networks': 390,
 'Boosting': 190,
 'Cellular neural networks': 159,
 'Chatbots': 318,
 'Cognitive systems': 98,
 'Collective intelligence': 101,
 'Collective learning': 4,
 'Commonsense reasoning': 73,
 'Computation theory': 59,
 'Computational and artificial intelligence': 2,
 'Computational chemistry': 6,
 'Computational complexity': 286,
 'Computational cybernetics': 43,
 'Computational intelligence': 246,
 'Computational statistics': 7,
 'Concept drift': 86,
 'Concurrent computing': 593,
 'Context awareness': 175,
 'Context management': 13,
 'Conversational artificial intelligence': 52,
 'Convolutional neural networks': 992,
 'Cooperative systems': 116,
 'Deep learning': 1700,
 'Deep reinforcement learning': 148,
 'Diffusion models': 217,
 'Dimensionality reduction': 157,
 'Echo state networks': 41,
 'Edge AI': 88,
 'Electronic learning': 370,
 'Ensemble learning': 172,
 'Evolutionary computation': 277,
 'Evolutionary robotics': 17,
 'Expert systems': 249,
 'Explainable AI': 132,
 'Extreme learning machines': 103,
 'Federated learning': 227,
 'Feedforward neural networks': 204,
 'Few shot learning': 126,
 'Foundation models': 125,
 'Fuzzy control': 251,
 'Fuzzy logic': 362,
 'Fuzzy neural networks': 181,
 'Fuzzy systems': 365,
 'Gated recurrent units': 109,
 'Generative AI': 206,
 'Generative Pre-trainer transformer': 60,
 'Genetic algorithms': 501,
 'Genetic operators': 70,
 'Graph convolutional networks': 123,
 'Graph neural networks': 171,
 'Greedy algorithms': 134,
 'Hebbian theory': 107,
 'High dimensional data': 44,
 'Hopfield neural networks': 155,
 'Hybrid intelligent systems': 133,
 'Hybrid learning': 107,
 'Hyper-intelligent systems': 4,
 'Hyperparameter optimization': 118,
 'Imitation learning': 99,
 'Immersive learning': 104,
 'Incremental learning': 115,
 'Inference mechanisms': 104,
 'Intelligent automation': 76,
 'Intelligent robots': 190,
 'Intelligent systems': 476,
 'Knowledge acquisition': 167,
 'Knowledge based systems': 329,
 'Knowledge discovery': 153,
 'Knowledge engineering': 490,
 'Knowledge representation': 195,
 'Large language models': 494,
 'Learning automata': 126,
 'Learning management systems': 127,
 'Learning systems': 426,
 'Linear predictive coding': 122,
 'Logic': 417,
 'Long short term memory': 282,
 'Machine intelligence': 137,
 'Machine learning': 1501,
 'Machine listening': 60,
 'Mobile agents': 173,
 'Model compression': 84,
 'Multi-armed bandit problem': 55,
 'Multi-layer neural network': 178,
 'Multilayer perceptrons': 145,
 'Multivalued logic': 113,
 'Neural architecture search': 101,
 'Neural network compression': 49,
 'Neural network hardware': 167,
 'Neural networks': 2031,
 'One shot learning': 37,
 'Particle swarm optimization': 254,
 'Pattern analysis': 195,
 'Perception evolution networks': 10,
 'Prediction methods': 130,
 'Predictive coding': 111,
 'Predictive encoding': 26,
 'Predictive models': 1821,
 'Probabilistic logic': 303,
 'Prompt engineering': 134,
 'Radial basis function networks': 121,
 'Random forests': 302,
 'Recurrent neural networks': 359,
 'Reinforcement learning': 353,
 'Relevance vector machines': 40,
 'Representation learning': 222,
 'Reservoir computing': 114,
 'Residual neural networks': 170,
 'Retrieval augmented generation': 132,
 'Robot learning': 80,
 'Self-organizing feature maps': 65,
 'Self-supervised learning': 211,
 'Semisupervised learning': 161,
 'Spiking neural networks': 132,
 'Stability plasticity': 26,
 'Statistical learning': 111,
 'Sufficient conditions': 233,
 'Supervised learning': 309,
 'Support vector machines': 935,
 'Takagi-Sugeno model': 140,
 'Text to image': 161,
 'Text to video': 90,
 'Tiny machine learning': 88,
 'Transfer learning': 334,
 'Turing completeness': 6,
 'Unsupervised learning': 205,
 'Virtual artifact': 4,
 'Virtual assistants': 121,
 'Weak supervision': 65}

In [14]:
others = 0
for terms in ieee_10["IEEE Terms"]:
    for term in terms.split(";"):
        if term in ieee_terms_counts_10:
            ieee_terms_counts_10[term] += 1
        else:
            others += 1
print(others)
pprint(ieee_terms_counts_10)

57018
{'AI accelerators': 14,
 'Active learning': 13,
 'Adversarial machine learning': 12,
 'Affective computing': 15,
 'Artificial general intelligence': 12,
 'Artificial intelligence': 169,
 'Artificial neural networks': 121,
 'Association rule learning': 14,
 'Attention mechanisms': 29,
 'Autoencoders': 17,
 'Automated machine learning': 16,
 'Autonomous mental development': 10,
 'Autonomous robots': 12,
 'Autonomous systems': 14,
 'Backpropagation': 22,
 'Bidirectional long short term memory': 10,
 'Bio-inspired computing': 12,
 'Biological neural networks': 71,
 'Boosting': 19,
 'Cellular neural networks': 23,
 'Chatbots': 46,
 'Cognitive systems': 13,
 'Collective intelligence': 10,
 'Collective learning': 4,
 'Commonsense reasoning': 10,
 'Computation theory': 10,
 'Computational and artificial intelligence': 1,
 'Computational chemistry': 6,
 'Computational complexity': 37,
 'Computational cybernetics': 10,
 'Computational intelligence': 27,
 'Computational statistics': 7,
 'Concept drift': 10,
 'Concurrent computing': 81,
 'Context awareness': 32,
 'Context management': 10,
 'Conversational artificial intelligence': 10,
 'Convolutional neural networks': 135,
 'Cooperative systems': 14,
 'Deep learning': 218,
 'Deep reinforcement learning': 23,
 'Diffusion models': 23,
 'Dimensionality reduction': 27,
 'Echo state networks': 14,
 'Edge AI': 10,
 'Electronic learning': 74,
 'Ensemble learning': 18,
 'Evolutionary computation': 30,
 'Evolutionary robotics': 10,
 'Expert systems': 28,
 'Explainable AI': 16,
 'Extreme learning machines': 13,
 'Federated learning': 21,
 'Feedforward neural networks': 31,
 'Few shot learning': 19,
 'Foundation models': 18,
 'Fuzzy control': 19,
 'Fuzzy logic': 47,
 'Fuzzy neural networks': 22,
 'Fuzzy systems': 44,
 'Gated recurrent units': 15,
 'Generative AI': 27,
 'Generative Pre-trainer transformer': 12,
 'Genetic algorithms': 73,
 'Genetic operators': 11,
 'Graph convolutional networks': 12,
 'Graph neural networks': 14,
 'Greedy algorithms': 14,
 'Hebbian theory': 10,
 'High dimensional data': 10,
 'Hopfield neural networks': 27,
 'Hybrid intelligent systems': 22,
 'Hybrid learning': 12,
 'Hyper-intelligent systems': 4,
 'Hyperparameter optimization': 17,
 'Imitation learning': 11,
 'Immersive learning': 13,
 'Incremental learning': 13,
 'Inference mechanisms': 10,
 'Intelligent automation': 12,
 'Intelligent robots': 17,
 'Intelligent systems': 66,
 'Knowledge acquisition': 17,
 'Knowledge based systems': 49,
 'Knowledge discovery': 23,
 'Knowledge engineering': 60,
 'Knowledge representation': 34,
 'Large language models': 58,
 'Learning automata': 14,
 'Learning management systems': 11,
 'Learning systems': 62,
 'Linear predictive coding': 14,
 'Logic': 63,
 'Long short term memory': 41,
 'Machine intelligence': 18,
 'Machine learning': 219,
 'Machine listening': 12,
 'Mobile agents': 18,
 'Model compression': 12,
 'Multi-armed bandit problem': 10,
 'Multi-layer neural network': 21,
 'Multilayer perceptrons': 22,
 'Multivalued logic': 12,
 'Neural architecture search': 11,
 'Neural network compression': 12,
 'Neural network hardware': 14,
 'Neural networks': 259,
 'One shot learning': 18,
 'Particle swarm optimization': 24,
 'Pattern analysis': 23,
 'Perception evolution networks': 10,
 'Prediction methods': 17,
 'Predictive coding': 18,
 'Predictive encoding': 11,
 'Predictive models': 209,
 'Probabilistic logic': 38,
 'Prompt engineering': 15,
 'Radial basis function networks': 14,
 'Random forests': 32,
 'Recurrent neural networks': 42,
 'Reinforcement learning': 43,
 'Relevance vector machines': 10,
 'Representation learning': 23,
 'Reservoir computing': 17,
 'Residual neural networks': 23,
 'Retrieval augmented generation': 14,
 'Robot learning': 12,
 'Self-organizing feature maps': 11,
 'Self-supervised learning': 41,
 'Semisupervised learning': 14,
 'Spiking neural networks': 14,
 'Stability plasticity': 12,
 'Statistical learning': 13,
 'Sufficient conditions': 28,
 'Supervised learning': 57,
 'Support vector machines': 120,
 'Takagi-Sugeno model': 15,
 'Text to image': 22,
 'Text to video': 14,
 'Tiny machine learning': 14,
 'Transfer learning': 45,
 'Turing completeness': 6,
 'Unsupervised learning': 18,
 'Virtual artifact': 4,
 'Virtual assistants': 16,
 'Weak supervision': 10}

# random prob

In [22]:
df = ieee_ai_10.drop_duplicates()

In [18]:
# make term-to-path dict

def make_term_to_path_dict(term_to_path_dict, subtree, current_path):
    if subtree is None:
        return
    for term in subtree:
        term_path = [*current_path, term]
        #print(term, term_path, subtree[term])
        if term in term_to_path_dict:
            term_to_path_dict[term].append(term_path)
        else:
            term_to_path_dict[term] = [term_path]
        make_term_to_path_dict(term_to_path_dict, subtree[term], term_path)


term_to_path_dict = {}
make_term_to_path_dict(term_to_path_dict, IEEE_TAX, [])

In [106]:
def calc_f1(r,p):
    if r==0 and p==0:
        return 0
    return 2*p*r/(r+p)

def calc_random_prob_step(step, subtax, paths, stop_prob_factor):
    recall = 0
    precision = 0
    f1_score = 0

    p_stop = stop_prob_factor/(len(subtax)+stop_prob_factor)
    p_continue = len(subtax)/(len(subtax)+stop_prob_factor)
    p_specific_key = 1/(len(subtax)+stop_prob_factor)

    # if it stops:
    r = (step/(step+min([len(path) for path in paths])))
    p = 1
    f1 =  calc_f1(r,p)
    recall += p_stop * r
    precision += p_stop * p
    f1_score += p_stop * f1

    # if it continues
    for key in subtax.keys():
        key_paths = []
        for path in paths:

            # correct path:
            if path[0] == key:
                if len(path) == 1:
                    # path fully predicted
                    r=1
                    subtax_length = 0 if subtax[key] is None else len(subtax[key])
                    p_key_stop = stop_prob_factor/(subtax_length+stop_prob_factor)
                    prec_key_stop = 1
                    p_key_continue = (1-p_key_stop)
                    prec_key_continue = (step+1)/(step+2)
                    p = prec_key_stop*p_key_stop + prec_key_continue*p_key_continue
                    f1 = p_key_stop*calc_f1(r, prec_key_stop) + prec_key_continue*calc_f1(r, prec_key_continue)

                    f1_score += p_specific_key * f1
                    recall += p_specific_key * r
                    precision += p_specific_key * p
                else:
                    #print(path)
                    key_paths.append(path[1:])
            
        # if this key leads to any gt path
        if len(key_paths):
            r, p, f1 = calc_random_prob_step(step+1, subtax[key], key_paths, stop_prob_factor)
            recall += r*p_specific_key
            precision += p*p_specific_key
            f1_score += f1*p_specific_key
        
        # otherwise:
        else:
            r = step/(step+min([len(path) for path in paths]))
            p = step/(step+1)
            f1 = calc_f1(r, p)
            recall += p_specific_key * r
            precision += p_specific_key * p
            f1_score += p_specific_key * f1
    return recall, precision, f1_score

In [116]:
ignore_first = True#False


def calc_random_prob(paths, stop_prob_factor=1.0):
    if ignore_first:
        reduced_paths = []
        for path in paths:
            if len(path)>1:
                reduced_paths.append(path[1:])
        #print("red:", reduced_paths)
        recall, precision, f1_score = calc_random_prob_step(0, IEEE_TAX["Computational and artificial intelligence"], reduced_paths, stop_prob_factor)
    else:
        recall, precision, f1_score = calc_random_prob_step(0, IEEE_TAX, paths, stop_prob_factor)
    return recall, precision, f1_score

In [117]:
def get_results(stop_prob_factor=1.):
    results = pd.DataFrame(columns=["recall", "precision", "f1_score"])
    for key in df.index:
        gt_terms = df.loc[key, "IEEE Terms"]
        gt_terms = gt_terms.split(";")

        relevant_gt_terms_paths = []
        for gt_term in gt_terms:
            if gt_term in ieee_strings:    
                relevant_gt_terms_paths.extend(term_to_path_dict[gt_term])


        recall, precision, f1_score = calc_random_prob(relevant_gt_terms_paths, stop_prob_factor=stop_prob_factor)

        results.loc[key] = (recall, precision, f1_score)
    return results
results = get_results()

In [118]:
results

              recall  precision  f1_score
ieee_87     0.051504   0.219182  0.061233
ieee_88     0.054225   0.221393  0.064406
ieee_89     0.051504   0.219182  0.061233
ieee_90     0.194361   0.293162  0.113954
ieee_91     0.052360   0.220323  0.062753
...              ...        ...       ...
ieee_54328  0.049639   0.218112  0.059580
ieee_54329  0.049639   0.218112  0.059580
ieee_54330  0.077700   0.222364  0.078968
ieee_54331  0.049639   0.218112  0.059580
ieee_54332  0.052360   0.220323  0.062753

[1510 rows x 3 columns]

In [119]:
for i in range(1,30):
    print(get_results(i/10).mean())

recall       0.129906
precision    0.147632
f1_score     0.119840
dtype: float64
recall       0.127389
precision    0.162154
f1_score     0.118173
dtype: float64
recall       0.124991
precision    0.176194
f1_score     0.116550
dtype: float64
recall       0.122700
precision    0.189776
f1_score     0.114968
dtype: float64
recall       0.120505
precision    0.202922
f1_score     0.113429
dtype: float64
recall       0.118398
precision    0.215653
f1_score     0.111929
dtype: float64
recall       0.116373
precision    0.227989
f1_score     0.110469
dtype: float64
recall       0.114423
precision    0.239948
f1_score     0.109047
dtype: float64
recall       0.112544
precision    0.251547
f1_score     0.107662
dtype: float64
recall       0.110730
precision    0.262802
f1_score     0.106312
dtype: float64
recall       0.108978
precision    0.273729
f1_score     0.104997
dtype: float64
recall       0.107285
precision    0.284341
f1_score     0.103715
dtype: float64
recall       0.105646
precision    0.294651
f1_score     0.102465
dtype: float64
recall       0.104059
precision    0.304673
f1_score     0.101246
dtype: float64
recall       0.102521
precision    0.314419
f1_score     0.100056
dtype: float64
recall       0.101029
precision    0.323899
f1_score     0.098895
dtype: float64
recall       0.099582
precision    0.333125
f1_score     0.097762
dtype: float64
recall       0.098178
precision    0.342106
f1_score     0.096656
dtype: float64
recall       0.096814
precision    0.350853
f1_score     0.095575
dtype: float64
recall       0.095488
precision    0.359373
f1_score     0.094520
dtype: float64
recall       0.094199
precision    0.367676
f1_score     0.093488
dtype: float64
recall       0.092945
precision    0.375770
f1_score     0.092480
dtype: float64
recall       0.091724
precision    0.383663
f1_score     0.091495
dtype: float64
recall       0.090536
precision    0.391362
f1_score     0.090531
dtype: float64
recall       0.089379
precision    0.398875
f1_score     0.089588
dtype: float64
recall       0.088252
precision    0.406207
f1_score     0.088665
dtype: float64
recall       0.087153
precision    0.413365
f1_score     0.087762
dtype: float64
recall       0.086081
precision    0.420355
f1_score     0.086879
dtype: float64
recall       0.085036
precision    0.427184
f1_score     0.086013
dtype: float64