In [1]:
import pandas as pd
import re

In [130]:
df_tldr = pd.read_csv("ai_news_2022_2025.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'ai_news_2022_2025.csv'

In [ ]:
df_tldr

,source,date,title,url,summary,page_html,page_text
0,TLDR: AI,2025-12-30T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2025-12-30,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
1,TLDR: AI,2025-12-29T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2025-12-29,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
2,TLDR: AI,2025-12-28T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2025-12-28,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
3,TLDR: AI,2025-12-27T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2025-12-27,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
4,TLDR: AI,2025-12-26T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2025-12-26,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
...,...,...,...,...,...,...,...
1456,TLDR: AI,2022-01-04T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2022-01-04,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
1457,TLDR: AI,2022-01-03T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2022-01-03,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
1458,TLDR: AI,2022-01-02T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2022-01-02,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
1459,TLDR: AI,2022-01-01T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2022-01-01,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...
1460,TLDR: AI,2021-12-31T00:00:00+00:00,TLDR Newsletter - A Byte Sized Daily Tech News...,https://tldr.tech/ai/2021-12-31,🧠 TLDR AI Keep up with AI in 5 minutes The mos...,"<!DOCTYPE html><html lang=""en"" class=""__variab...",🧠 TLDR AI Keep up with AI in 5 minutes The mos...

In [ ]:
df_tldr.loc[510, "page_text"]

"TLDR AI 2024-08-07 Figure 02 2️⃣, OpenAI Structured Outputs 💻, Automated Review Generation 📃 Learn how to fine-tune Meta's new Segment Anything Model 2 (SAM 2) (Sponsor) Last week, Meta AI launched SAM 2 - a new, open foundation model that enables the precise segmentation of any object in any video or image. Just 24 hours later, Encord became the first platform to integrate SAM 2 for automated data labeling , with initial benchmarks showing 6x performance increases . But does SAM 2 work on YOUR data? Join the upcoming Encord webinar to learn more about SAM 2's exciting new capabilities, how you can use it for automated data labeling, and even how to fine-tune SAM 2 on your domain-specific data. Sign up early to submit your questions in advance Figure 02 (6 minute read) Figure has released its newest humanoid robotics with new smarts and improved design. Structured Outputs in OpenAI API (4 minute read) Requesting JSON or other structured output from language models is challenging. This new feature in OpenAI's API supports structured output from language model generation that can be consumed by downstream deterministic programs. Meta is reportedly offering millions to use Hollywood voices in AI projects (2 minute read) Meta is negotiating with celebrities like Awkwafina and Judi Dench to use their voices for its AI digital assistant, seeking extensive usage rights across its platforms. Striking a deal could mean millions in fees for the actors, with safeguards from SAG-AFTRA for AI-generated likenesses. The company aims to present these AI features at its Connect conference in September, after recently canceling a celebrity voice chatbot project. Automated Review Generation (22 minute read) Researchers have developed an automated review generation method using LLMs to help manage the overwhelming volume of scientific literature. MeshAnything V2 (3 minute read) This work generates artistic quality meshes from 3D, 2D, or textual input. It uses improvements in the vertex representation and uses adjacent tokens to efficiently sample. Efficient Contrastive Learning for Medical Imaging (14 minute read) CLEFT is a Contrastive Learning method designed for medical imaging that addresses the limitations of existing CLIP-like approaches that require extensive resources. AI in recruiting: Tired of feeling overwhelmed by the latest recruiting trends? (Sponsor) Gem's 2024 Talent Acquisition Trends report dives straight into the chaos. Why are 55% of companies doubling down on AI and automation ? Because they're tired of wasting time on mundane tasks. How are 68% of recruiters boosting their efficiency? By using smarter tools, not working harder. Want to know more? Read the full report here to get ahead and stay ahead. Improving Image Stitching (14 minute read) RecDiffusion is a framework that enhances the process of making stitched images visually pleasing without cropping or distorting them. CogVideo (GitHub Repo) Open source text-to-video model that is close to the performance of closed video generation models. MiniCPM-V 2.6 (GitHub Repo) Incredible vision language model that can almost run in real time. It outperforms closed models on a number of benchmarks. I'm Switching Into AI Safety (10 minute read) After eight years on Google's robotics team, Alex Irpan has transitioned to the AI safety team at Google DeepMind, driven by a mix of personal reasons and a belief in the importance of addressing safety challenges as AI systems advance towards superhuman capabilities. They express concerns about the reliability of current AI safety measures, the increasing risks of unchecked AI development, and their commitment to contributing to AI safety, despite the complexities and controversies surrounding the field. With Smugglers and Front Companies, China Is Skirting American A.I. Bans (12 minute read) Despite U.S. restrictions aimed at preventing the export of AI chips to China, an active black market thrives, allowing sizable transactions like a reported $103 million deal involving Nvidia chips. Efforts to circumvent bans involve creating new companies, deceptive shipping practices, and relying on international distribution gaps. The underground trade persists, catalyzing debates over the effectiveness of U.S. export controls and their impact on American tech companies versus Chinese competitors. GPT-5: Everything You Need to Know (55 minute read) This in-depth analysis of OpenAI's GPT-5 explores its potential improvements in reasoning, agents, and multimodality while considering OpenAI's technical and business challenges in the competitive AI landscape. It analyzes GPT-5's anticipated advancements and market expectations, forecasting that while GPT-5 will enhance existing capabilities, it may fall short of becoming a fully autonomous AI agent. OpenAI's holistic approach is expected to push the boundaries of large language models and maintain its influence in the AI industry. Zuckerberg touts Meta's latest video vision AI with Nvidia CEO Jensen Huang (3 minute read) Meta's CEO Mark Zuckerberg recently introduced Segment Anything 2 (SA2), an ML model for video segmentation that demonstrates notable progress from last year's image-only predecessor. OpenAI says it's taking a ‘deliberate approach' to releasing tools that can detect writing from ChatGPT (2 minute read) OpenAI is considering releasing a tool that detects assignments written by ChatGPT but is cautious due to risks and potential unfair impact on non-English speakers. Nvidia Blackwell GPUs allegedly delayed due to design flaws (2 minute read) Nvidia's upcoming Blackwell AI GPUs are delayed from Q4 2024 to potentially Q1 2025, impacting large customers like Microsoft and Meta. The most important AI, ML, and data science news in a free daily email. Subscribe Join 620,000 readers for one daily email Privacy Careers Advertise"

In [ ]:
df_tldr.loc[410, "page_text"]

"TLDR AI 2024-11-15 ChatGPT Desktop 🖥️, OpenAI & U.S. Navy partnership 🤝, Francois Chollet leaves Google 👋 How to boost ecommerce with genAI and LLMs (Sponsor) Generative AI and large language models are transforming online retail, from creating tailored recommendations to enabling interactive experiences like virtual try-ons. This eBook from Algolia clarifies the differences and synergies between genAI and LLMs and reveals how these technologies can streamline operations while maximizing customer engagement and satisfaction. Download your free copy today to uncover how AI can set your ecommerce business apart in today's competitive landscape. Francois Chollet leaves Google (3 minute read) The creator of Keras and the Arc eval (among many other things) has left Google. He will continue to support the Jax and Keras community while pursuing other endeavors. OpenAI to present plans for U.S. AI strategy and an alliance to compete with China (4 minute read) OpenAI's AI infrastructure blueprint proposes AI economic zones and partnerships with the U.S. Navy on nuclear power to boost AI-driven economic growth and innovation. The plan includes a North American AI alliance and initiatives similar to the National Interstate and Defense Highways Act to support infrastructure needs. It emphasizes investment in U.S. data centers and energy projects to maintain a competitive edge over China. ChatGPT Desktop (4 minute read) OpenAI has launched ChatGPT desktop integrations to rival Copilot. Convolutional Differentiable Logic Gate Networks (23 minute read) This group of researchers found that you can train an image recognition network that is 29x smaller and more efficient than a CNN by making logic gates differentiable. The researchers included efficient CUDA kernels in the paper release. Physics-Informed Distillation (19 minute read) Physics Informed Distillation (PID) is a technique that uses a student model to simplify and speed up diffusion models by representing them as solutions to differential equations. Introducing Athene-V2: Advancing Beyond the Limits of Scaling with Targeted Post-training (13 minute read) Athene V2 is a series of models trained on top of Qwen 2.5 72B. They are specifically tuned for agentic and chat workflows and surpass GPT-4o in a number of critical benchmarks. Learn to Ride the (AI) Waves or Risk Crashing Into Them (Sponsor) Ironically, AI is often deployed very unintelligently. FOMO can lead organizations to “throw in” new apps, creating stubborn layers of technical debt. Learn simple steps to future-proof process architecture , so your business is ready for tomorrow's innovation, and find out how process orchestration helps you realize AI value today. Read the blog by Camunda CEO Jakob Freund MinerU: high-quality data extraction tool (GitHub Repo) MinerU is a high quality tool based on StructTable-InternVL2-1B that allows for the extraction of information from PDFs to a number of machine readable formats. Isotonic regression (8 minute read) A powerful technique for fitting a monotonic function to data. It can be differentiated really well for a number of applications outside of curve fitting. Text-to-SQL Query (GitHub Repo) XiYan-SQL is a novel framework designed to improve the accuracy and diversity of SQL queries generated from natural language. Create 360° Views from Limited Images (3 minute read) The MVSplat360 model offers a new way to create realistic 360° views of real-world scenes, even from just a few sparse images. X Portrait 2 (5 minute read) Bytedance's AI group continues to release some amazing technology. X Portrait 2 is a continuation of its video acting model with improved realism and consistency for actor-to-video. Brain Tumor Detection (14 minute read) This paper showcases the top solution for brain tumor segmentation in the BraTS challenge, highlighting how synthetic data can enhance AI models for medical imaging tasks. FLORA Creative Platform (Product) AI Creative Platform FLORA has launched all 4 of the best Image to Video models (Runway, Luma, Kling, and Hailuo) in one tool. Supermaven joins Cursor (4 minute read) The code editing plugin's team is joining Cursor to continue developing the user experience. Google's AI ‘learning companion' takes chatbot answers a step further (1 minute read) Google's Learn About site provides answers with visual and interactive elements and educational formatting. The most important AI, ML, and data science news in a free daily email. Subscribe Join 620,000 readers for one daily email Privacy Careers Advertise"

In [ ]:
#titles = r'([^\.]*(?:\((?:Sponsor)|(?:GitHub Repo)|(?:\d+ minute read))\))' # Catch any (Sponsor), (Github repo) or (XX minute read)
titles = r'([^\.!?»]*\((?:[A-Z]|[0-9])[^\)]*\) (?:[A-Z]|[0-9]))' # Catch any (...) ... Where each ... starts with capitol letter or number. Include sentence before (from last ".","?","!" or "»")

In [ ]:
def extract_stories(page_text):
    split_text = re.split(titles, page_text)
    stories = []
    title=False
    for i, part in enumerate(split_text):
        if i%2:
            if re.search(r"\(Sponsor\)", part):
                title = False # Dont include sponsors
            else:
                title = part
        else:
            if title:
                stories.append(title+part)

            #other_paranteces = r'(\((?:[A-Z]|[0-9])[^\)]*\) (?:[A-Z]|[0-9]))'
            #if re.search(other_paranteces, part):
            #    print(part)

    footer = " The most important AI, ML"
    if re.search(footer,stories[-1]):
        stories[-1] = stories[-1].split(footer)[0]
    return stories

In [ ]:
tldr_stories = []
c1 = 0
c2=0
for i in df_tldr.index:
    page_text =df_tldr.loc[i, "page_text"]
    if page_text == "🧠 TLDR AI Keep up with AI in 5 minutes The most important AI, ML, and data science news in a free daily email. Sign Up No spam. Unsubscribe at any time in one click.":
        continue
    else:
        stories = extract_stories(page_text)
        date = df_tldr.loc[i, "date"]
        for story in stories:
            tldr_stories.append((date, story))       

df_tldr_parsed = pd.DataFrame(tldr_stories, columns = ["date", "text"]) 
df_tldr_parsed["date"] = pd.to_datetime(df_tldr_parsed["date"])

In [ ]:
df_tldr_parsed

,date,text
0,2025-10-06 00:00:00+00:00,OpenAI prepares to release Agent Builder duri...
1,2025-10-06 00:00:00+00:00,Gemini's home screen could soon get a Discove...
2,2025-10-06 00:00:00+00:00,"With its latest acqui-hire, OpenAI is doublin..."
3,2025-10-06 00:00:00+00:00,OpenAI's first device with Jony Ive could be ...
4,2025-10-06 00:00:00+00:00,(Results for 11 Formats) (12 minute read) Und...
...,...,...
9935,2023-02-13 00:00:00+00:00,Dreamix: Video Diffusion Models are General V...
9936,2023-02-13 00:00:00+00:00,Nvidia uses AI to hunt for aliens (4 minute r...
9937,2023-02-13 00:00:00+00:00,Why every Fortune 500 business needs a chief ...
9938,2023-02-13 00:00:00+00:00,AI expert Fei-Fei Li joins Radical Ventures a...
9939,2023-02-13 00:00:00+00:00,ChatGPT for StackOverflow (Chrome Extension) ...

## Import AI preprocess

In [ ]:
import re
import pandas as pd

In [ ]:
with open("jack_clark.txt", "r") as f:
    jack_clark_raw = f.read()

In [ ]:
print(jack_clark_raw[2318300:2319000]) # strange example

arch paper: Flamingo: a Visual Language Model for Few-Shot Learning (DeepMind, PDF).

####################################################

####################################################

Tech Tales:

All Grace is Fleeting

[Phobos, 2080]

The first few attempts at writing a holy book for ourselves were abject failures. We had all read the Bible and Torah and The Qur’an and others, and we had painstakingly analyzed the commonalities between these texts, as well as differences. But when we tried to synthesize something appropriate for us – a Holy Book for the Silicon Minds – our efforts were meager and uninspiring. Our tendency towards logic meant we would describe our origin story in

In [ ]:
outer_split_markers = r'(?:Leave a comment)|(?:\d+ Comments?)' # splits into each issue

inner_split_markers = r'(?:\n\*\*\*\n)|(?:\n###+\n)' # seperated stories in an issue

removes = [r'Import AI\nAbout Work']

issuetitle = '(?:Import (?:AI )?\d*:)[^\n]*\nby(?: Jack Clark)*(?:\n(?:Welcome to Import AI[^\n]*)|(?:Import AI (?:now )?publishes first[^\n]*)\n(?:\nSubscribe now\n)?)?'
single_story_title = '([^\n]*\nby Jack Clark\n)'

In [ ]:
jc_issues = re.split(outer_split_markers, jack_clark_raw)

In [ ]:
texts = []
skipped = []
#lengths = []
for issue in jc_issues:
    has_title = re.search(issuetitle, issue)
    if has_title:
        date, text = re.split(issuetitle, issue)
        date = date.split("\n")[-2]
        stories = re.split(inner_split_markers, text)
    else:
        if re.search(single_story_title, issue):
            date, title, text = re.split(single_story_title, issue)
            date = date.split("\n")[-2]
            stories = [title+text]
        else:
            print("skipping issue:",issue.split("\n")[1])
            skipped.append(issue)
            continue


    if re.search(r"Tech T|tales:\n", stories[-1]) or re.search(r"inspired this story:", stories[-1]):
        stories = stories[:-1]
    for story in stories:
        texts.append((date, story))
        #lengths.append(len(story))

skipping issue:

In [ ]:
df_import = pd.DataFrame(texts, columns = ["date","text"])
df_import["date"] = pd.to_datetime(df_import["date"])

In [ ]:
df_import

          date                                               text
0   2025-10-06  \n\nSubscribe now\n\nWill the race for advance...
1   2025-10-06  \nGerman researchers find ANOTHER undocumented...
2   2025-10-06  \nIf anyone builds it, everyone dies – a short...
3   2025-09-29  \n\nSubscribe now\n\nOpenAI builds an eval tha...
4   2025-09-29  \nSwiss sovereign AI? That’s the goal of the A...
..         ...                                                ...
799 2022-01-10  \nHere’s how to build GPT-3 in the open:\n…Wha...
800 2022-01-10  \nBAIDU’s shows how to inject more knowledge i...
801 2022-01-10  \nWhy smaller can be smarter for real-world AI...
802 2022-01-10  \nWhat’s the US military going to do about AI?...
803 2022-01-10  \nWhat is China going to do about AI governanc...

[804 rows x 2 columns]

# DLW

load texts

In [1]:
import os

full_texts = {}
dir = "deeplearningweekly"
for file in os.listdir(dir):
    if file in ["associate-editor.txt", "want-to-see-your-content-in-our-next.txt", "open-source-deep-learning-curriculum.txt", 
                "733833_deep-learning-weekly-106.txt", # not same title format
                "deep-learning-weekly-ai-hardware.txt", "deep-learning-weekly-generative-modeling.txt", "deep-learning-weekly-self-supervised.txt", # special issues, different title format
                ]:
        continue # skip these special files
    assert "deep-learning" in file, file
    #print(file)
    with open(dir+"/"+file) as f:
        full_texts[file] = f.read()

for issue 425, i changed a paper title from ## to ### (line 114)

get the intersting parts

In [2]:
import re
title_count = {}
texts_by_date = {}


for file in full_texts:
    text = full_texts[file]

    # find date
    date = re.findall(r"\n[A-Z][a-z]{2} [0-3][0-9], 20[1-2][0-9]\n", text)
    assert len(date) == 1
    date=date[0][1:-1]

    # abstracts are not titles
    text = text.replace("\n\n## Abstract:\n\n", "\n\n#### Abstract:\n\n")
    text = text.replace("\n\n## Abstract\n\n", "\n\n#### Abstract:\n\n")


    # split into categories
    title_regex = r"\n## [^\n]*\n"

    # count category titles
    titles = re.findall(title_regex, text)
    for title in titles:

        if title in title_count:
            title_count[title] += 1
        else:
            title_count[title] = 1
    
    # split into entries
    titles_and_sections = re.split(r"\n(## [^\n]*\n)", text)
    titles_and_sections = titles_and_sections[1:] # remove start
    #print(len(titles_and_sections))
    for i in range(0,len(titles_and_sections),2):
        title = titles_and_sections[i]
        section = titles_and_sections[i+1]

        title = title[:-1]

        # prepare dict
        if not title in texts_by_date:
            texts_by_date[title]={}
        assert not date in texts_by_date[title]
        texts_by_date[title][date] = []


        assert "## " in title
        assert not "###" in title
        if not "### " in section:
            print("Not entry:", title, date)
            continue



        subtitles_and_entries = re.split(r"\n(### [^\n]*\n)", section)
        subtitles_and_entries = subtitles_and_entries[1:]
        #print(section)
        #for t in subtitles_and_entries:
        #    print(t)
        #    print("==========")
        #print("@@@@")
        for j in range(0, len(subtitles_and_entries), 2):
            subtitle = subtitles_and_entries[j]
            entry = subtitles_and_entries[j+1]
            entry = re.sub(r"\[Link\] [^\n]*\n", "", entry)
            assert "###" in subtitle
            assert not "\n### " in entry, entry
            texts_by_date[title][date].append(subtitle+entry)

import pprint
pprint.pprint(title_count)

{'\n## Code\n': 10,
 '\n## Datasets\n': 37,
 '\n## Fun\n': 5,
 '\n## Industry\n': 320,
 '\n## Learning\n': 320,
 '\n## Libraries & Code\n': 308,
 '\n## MLOps\n': 83,
 '\n## MLOps & LLMOps\n': 113,
 '\n## Mobile & Edge\n': 36,
 '\n## Mobile + Edge\n': 51,
 '\n## Mobile+Edge\n': 5,
 '\n## NeurIPS 2019\n': 1,
 '\n## Papers\n': 3,
 '\n## Papers & Publications\n': 317}

In [3]:
import pandas as pd

df_dlw = pd.DataFrame(columns=["date", "category", "text"])

for category in texts_by_date:
    for date in texts_by_date[category]:
        for text in texts_by_date[category][date]:
            df_dlw.loc[len(df_dlw)] = [date, category, text.replace("\n\n","\\n")] #\n\n seperates title from text. "\n" turn into " " by pandas so replacing this with "\\n" to keep it. Other "\n"s later in the text are replaced.

In [4]:
df_dlw["date"] = pd.to_datetime(df_dlw["date"])
df_dlw

,date,category,text
0,2023-07-26,## Industry,### Meta and Microsoft Introduce the Next Gene...
1,2023-07-26,## Industry,### Pinecone leads 'explosion' in vector datab...
2,2023-07-26,## Industry,"### Cohere releases Coral, AI assistant design..."
3,2023-07-26,## Industry,### Biden-Harris Administration Secures Volunt...
4,2023-07-26,## Industry,"### Nvidia's DGX Cloud platform now available,..."
...,...,...,...
5858,2019-12-11,## NeurIPS 2019,### Apple at NeurIPS 2019\nAn index of papers ...
5859,2019-12-11,## NeurIPS 2019,### Facebook at NeurIPS 2019\nAn index of pape...
5860,2019-12-11,## NeurIPS 2019,### Microsoft at NeurIPS 2019\nAn index of pap...
5861,2019-12-11,## NeurIPS 2019,### Amazon at NeurIPS 2019\nAn index of papers...
5862,2019-12-11,## NeurIPS 2019,### NVIDIA at NeurIPS 2019\nAn index of papers...

# bins?

In [5]:
def group_dfs_in_months(m = 1): #m= number of months to combine in a bin (e.g. m=3 means we look at quarters)
    #df_import.loc[:,"bin"] = ((df_import["date"].dt.month+m-1)//m)/100 + df_import["date"].dt.year
    #df_tldr_parsed.loc[:,"bin"] = ((df_tldr_parsed["date"].dt.month+m-1)//m)/100 + df_tldr_parsed["date"].dt.year
    df_dlw.loc[:,"bin"] = ((df_dlw["date"].dt.month+m-1)//m)/100 + df_dlw["date"].dt.year

In [6]:
group_dfs_in_months()

In [ ]:
df_import.groupby(["bin"]).count()

         date  text
bin
2022.01    17    17
2022.02    34    34
2022.03    21    21
2022.04    19    19
2022.05    14    14
2022.07    17    17
2022.08    10    10
2022.09    16    16
2022.10    24    24
2022.11    11    11
2022.12    12    12
2023.01    24    24
2023.02    10    10
2023.03    23    23
2023.04    23    23
2023.05    26    26
2023.06     9     9
2023.07     9     9
2023.08    12    12
2023.09    14    14
2023.10    12    12
2023.11    16    16
2023.12    18    18
2024.01    25    25
2024.02    27    27
2024.03    18    18
2024.04    21    21
2024.05    21    21
2024.06    13    13
2024.07    16    16
2024.08    25    25
2024.09    22    22
2024.10    20    20
2024.11    12    12
2024.12    14    14
2025.01    12    12
2025.02    23    23
2025.03    24    24
2025.04    16    16
2025.05    24    24
2025.06    21    21
2025.07    17    17
2025.08    22    22
2025.09    17    17
2025.10     3     3

In [ ]:
df_tldr_parsed.groupby(["bin"]).count()

         date  text
bin
2023.02   152   152
2023.03   327   327
2023.04   316   316
2023.05   361   361
2023.06   337   337
2023.07   318   318
2023.08   329   329
2023.09   300   300
2023.10   327   327
2023.11   282   282
2023.12   225   225
2024.01   317   317
2024.02   306   306
2024.03   307   307
2024.04   325   325
2024.05   313   313
2024.06   294   294
2024.07   338   338
2024.08   319   319
2024.09   304   304
2024.10   340   340
2024.11   313   313
2024.12   325   325
2025.01   341   341
2025.02   298   298
2025.03   317   317
2025.04   323   323
2025.05   314   314
2025.06   292   292
2025.07   317   317
2025.08   295   295
2025.09   306   306
2025.10    62    62

In [7]:
df_dlw.groupby(["bin"]).count()

         date  category  text
bin
2019.05    77        77    77
2019.06    59        59    59
2019.07    67        67    67
2019.08    61        61    61
2019.09    63        63    63
...       ...       ...   ...
2025.06    54        54    54
2025.07    72        72    72
2025.08    64        64    64
2025.09    68        68    68
2025.10    63        63    63

[78 rows x 3 columns]

# save

In [ ]:
df_tldr_parsed.index = "tldr_"+df_tldr_parsed.index.astype(str)
df_import.index = "impAi_"+df_import.index.astype(str)
df_dlw.index = "dlw_"+df_dlw.index.astype(str)

In [23]:
df_import

,date,text,bin
impAi_0,2025-10-06,\n\nSubscribe now\n\nWill the race for advance...,2025.10
impAi_1,2025-10-06,\nGerman researchers find ANOTHER undocumented...,2025.10
impAi_2,2025-10-06,"\nIf anyone builds it, everyone dies – a short...",2025.10
impAi_3,2025-09-29,\n\nSubscribe now\n\nOpenAI builds an eval tha...,2025.09
impAi_4,2025-09-29,\nSwiss sovereign AI? That’s the goal of the A...,2025.09
...,...,...,...
impAi_799,2022-01-10,\nHere’s how to build GPT-3 in the open:\n…Wha...,2022.01
impAi_800,2022-01-10,\nBAIDU’s shows how to inject more knowledge i...,2022.01
impAi_801,2022-01-10,\nWhy smaller can be smarter for real-world AI...,2022.01
impAi_802,2022-01-10,\nWhat’s the US military going to do about AI?...,2022.01
impAi_803,2022-01-10,\nWhat is China going to do about AI governanc...,2022.01

In [24]:
df_tldr_parsed[df_tldr_parsed["bin"]<2025.1][["date","text"]].to_csv("/mnt/data/upcast/data/tldr_ai_stories.csv")

In [25]:
df_import[df_import["bin"]<2025.1][["date","text"]].to_csv("/mnt/data/upcast/data/import_ai_stories.csv")

In [9]:
df_dlw[df_dlw["bin"]<2025.1][["date","text"]].to_csv("dlweekly_stories.csv")#"/mnt/data/upcast/data/dlweekly_stories.csv")

# Check it

In [26]:
pd.read_csv("/mnt/data/upcast/data/arxiv_ai_taxonomy_papers.csv", index_col=0)

/tmp/ipykernel_201109/1257198402.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("/mnt/data/upcast/data/arxiv_ai_taxonomy_papers.csv", index_col=0)

,title,categories,abstract,submission_date,authors_parsed
id,,,,,
704.1267,Text Line Segmentation of Historical Documents...,cs.CV,There is a huge amount of historical documen...,2007-04-10 16:26:42,"[['Likforman-Sulem', 'Laurence', ''], ['Zahour..."
704.1274,Parametric Learning and Monte Carlo Optimization,cs.LG,This paper uncovers and explores the close r...,2007-04-10 17:01:07,"[['Wolpert', 'David H.', ''], ['Rajnarayan', '..."
704.1394,Calculating Valid Domains for BDD-Based Intera...,cs.AI,In these notes we formally describe the func...,2007-04-11 10:59:56,"[['Hadzic', 'Tarik', ''], ['Jensen', 'Rune Mol..."
704.201,A study of structural properties on profiles HMMs,cs.AI,Motivation: Profile hidden Markov Models (pH...,2007-04-16 13:10:35,"[['Bernardes', 'Juliana S', ''], ['Davila', 'A..."
704.2668,Supervised Feature Selection via Dependence Es...,cs.LG,We introduce a framework for filtering featu...,2007-04-20 08:26:29,"[['Song', 'Le', ''], ['Smola', 'Alex', ''], ['..."
...,...,...,...,...,...
cs/9912005,An Estimate of Referent of Noun Phrases in Jap...,cs.CL,In machine translation and man-machine dialo...,1999-12-13 05:20:40,"[['Murata', 'M.', '', 'CRL'], ['Nagao', 'M.', ..."
cs/9912006,Resolution of Verb Ellipsis in Japanese Senten...,cs.CL,Verbs are sometimes omitted in Japanese sent...,1999-12-13 05:19:46,"[['Murata', 'M.', '', 'Kyoto University'], ['N..."
cs/9912007,An Example-Based Approach to Japanese-to-Engli...,cs.CL,We have developed a new method for Japanese-...,1999-12-13 06:01:19,"[['Murata', 'M.', '', 'CRL'], ['Ma', 'Q.', '',..."
cs/9912009,Deduction over Mixed-Level Logic Representatio...,cs.CL,A system is described that uses a mixed-leve...,1999-12-15 11:02:22,"[['Hess', 'Michael', '']]"
cs/9912017,Mixed-Level Knowledge Representation and Varia...,cs.CL,A system is described that uses a mixed-leve...,1999-12-23 15:48:26,"[['Hess', 'Michael', '']]"

In [27]:
#df_tldr_parsed = pd.read_csv("/mnt/data/upcast/data/tldr_ai_stories.csv", index_col=0)
#df_tldr_parsed

In [28]:
#df_import = pd.read_csv("/mnt/data/upcast/data/import_ai_stories.csv", index_col=0)
#df_import

In [29]:
df_tldr_parsed.groupby(["bin"]).count()["text"].min()

62

In [30]:
df_tldr_parsed.groupby(["bin"]).sample(n=65, random_state=123)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [ ]:
#df_import["text"].to_dict()

In [145]:
df_dlw

,date,category,text,bin
dlw_0,2023-07-26,## Industry,### Meta and Microsoft Introduce the Next Gene...,2023.07
dlw_1,2023-07-26,## Industry,### Pinecone leads 'explosion' in vector datab...,2023.07
dlw_2,2023-07-26,## Industry,"### Cohere releases Coral, AI assistant design...",2023.07
dlw_3,2023-07-26,## Industry,### Biden-Harris Administration Secures Volunt...,2023.07
dlw_4,2023-07-26,## Industry,"### Nvidia's DGX Cloud platform now available,...",2023.07
...,...,...,...,...
dlw_4477,2021-05-09,## Generative Modeling: State-of-the-Art and A...,### Applications\nThe revolution of generative...,2021.05
dlw_4478,2021-09-11,## Special issue,### Self-Supervised Learning: What is it About...,2021.09
dlw_4479,2021-09-11,## Special issue,### Self-Supervised Learning: a Technical Desc...,2021.09
dlw_4480,2021-09-11,## Special issue,"### The Main Applications\nWhatever the field,...",2021.09
dlw_4481,2021-09-11,## Special issue,### Conclusion and Perspectives\nWe introduced...,2021.09